/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#0b1c30',
        'on-primary-fixed': '#001f26',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#004e5c',
        'tertiary-fixed-dim': '#b4c5ff',
        'primary-fixed-dim': '#4cd7f6',
        'surface-variant': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'surface-container': '#e5eeff',
        'secondary-fixed-dim': '#bec6e0',
        'tertiary-fixed': '#dbe1ff',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#0053db',
        'background': '#f8f9ff',
        'secondary': '#565e74',
        'on-secondary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-container': '#5c647a',
        'on-secondary-fixed-variant': '#3f465c',
        'on-tertiary-fixed-variant': '#003ea8',
        'surface-container-high': '#dce9ff',
        'primary': '#00687a',
        'inverse-on-surface': '#eaf1ff',
        'secondary-fixed': '#dae2fd',
        'inverse-primary': '#4cd7f6',
        'on-tertiary-fixed': '#00174b',
        'surface': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#003490',
        'tertiary-container': '#85a3ff',
        'outline-variant': '#bcc9cd',
        'on-error-container': '#93000a',
        'surface-dim': '#cbdbf5',
        'on-error': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-surface-variant': '#3d494c',
        'on-primary-container': '#00424f',
        'on-primary': '#ffffff',
        'inverse-surface': '#213145',
        'surface-tint': '#00687a',
        'primary-container': '#06b6d4',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'outline': '#6d797d',
        'primary-fixed': '#acedff',
        'secondary-container': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit-2xl': '3rem',
        'unit-md': '1rem',
        'unit-3xl': '4.5rem',
        'grid-margin-tablet': '2rem',
        'gutter-desktop': '2rem',
        'grid-margin-desktop': '3rem',
        'unit-xs': '0.5rem',
        'unit-2xs': '0.25rem',
        'gutter-mobile': '1rem',
        'unit-lg': '1.5rem',
        'grid-margin-mobile': '1.25rem',
        'unit-xl': '2rem',
        'unit-sm': '0.75rem',
        'unit-4xl': '6rem',
      },
      fontFamily: {
        'display': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-mobile': ['2.75rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['2rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['1.375rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['0.875rem', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
